version: 2

project_name: preflight

builds:
  - id: preflight
    main: ./main.go
    binary: preflight
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/phillips-jon/preflight/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - name: preflight
    repository:
      owner: phillips-jon
      name: homebrew-preflight
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Preflight CLI for launch readiness checks"
    homepage: "https://github.com/phillips-jon/preflight.sh"
    commit_author:
      name: "GitHub Actions"
      email: "actions@github.com"
    install: |
      bin.install "preflight"

dockers: []

release:
  prerelease: false

changelog:
  disable: true
